travis:
  secure:
    BINSTAR_TOKEN: GWl2n5SvIRP9+Tl9pqeJGwWe5LfM1p160eykMbf7jf4qTNKog9HTP1IBwVwOOZBWu2wXf+QwHOcbDnzOCldAMMHi9GnrnorSZ2S0ViqX9yA7wr869Grv0xY0mi/+wh94IRoX6Y7nomib/ZFYK7mXoVIV8CmOTa/xUfOQYUYyqS2jnnBRtKnQLrK1Qw8ST3yObyKHDNvoaPdiHvzC87E8yTewi4x7X64r1lX3Luhf97B58Lp0k+uBjnQLYTX4Qknj4or/Fgg+YYPovd6zn79zGUI25bkmIh/QP5TnAaYmChcF53qw2u07At6VE5WwrnZG7lne78k7oG6RzNeWyA7O18NhGxEQY2agnYhKXctW0veG9bcMzo1OcRHUAt8OkJhEYO62GxmLrAvNy2Mh/ePMzB4PSgwKRL6hAihI3CXgH/2FxobL+WUYVnYIIzHAlkl/zhJpRSd3jWFr5XqmBG458GeqxcBhWtXJMGNhqHNtMFcWsKFBl/iHYDHjbNGeTPXbrDqbfFS0Nwd6m7LgeTECvpvUL2n7IVhFvm6eEGUQTuChKvj/lhzAc5K/3sO2fRy1+5gEjKa74+JsmL8fBrjNfGItCob2BwYWVdgJIT8rVasoBbCMu/9YRRh1X3xHbAuDsPaheBcVDjIa4jn2FVPL5JnhMcxtrxRZO9CJee/EITE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
